---
  output:
  officedown::rdocx_document: 
    reference_docx: styles_reference3.docx
    pandoc_args: ["--metadata-file=header.yaml"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
library(officedown)
library(officer)
# objects used: fish2, inverts2
```

```{r echo=FALSE,tab.cap='Appendix Table B-1. Fish species encountered and identified during the 2022 Aleutian Islands bottom trawl survey.', tab.id='b-specieslistfish',  tab.cap.style = "Table Caption"}
fish2 %>% 
  flextable(col_keys = c("FAMILY","COMMON_NAME","dummy_col")) %>%
  flextable::mk_par(
    j = "dummy_col",
    value = as_paragraph(as_i(species_2), " ", new_suffix)
  ) %>%
  set_header_labels(
    dummy_col = "Species name",
    FAMILY = "Family",
    COMMON_NAME = "Common name"
  ) %>%
  theme_vanilla() %>%
  fontsize(size = 9, part = "all") %>%
  width(j = 1, width = 2, unit = "in") %>%
  width(j = 2, width = 2, unit = "in") %>%
  width(j = 3, width = 2, unit = "in") %>%
  line_spacing(space = 1)
```

<br />

```{r echo=FALSE,tab.cap='Appendix Table B-2. Invertebrate species encountered and identified during the 2022 Aleutian Islands bottom trawl survey.', tab.id='b-specieslistinverts',  tab.cap.style = "Table Caption"}
inverts2 %>% 
  flextable(col_keys = c("PHYLUM","COMMON_NAME","dummy_col")) %>%
  flextable::mk_par(
    j = "dummy_col",
    value = as_paragraph(as_i(species_2), " ", new_suffix)
  ) %>%
  set_header_labels(
    dummy_col = "Species name",
    PHYLUM = "Phylum",
    COMMON_NAME = "Common name"
  ) %>%
  theme_vanilla() %>%
  fontsize(size = 9, part = "all") %>%
  width(j = 1, width = 2, unit = "in") %>%
  width(j = 2, width = 2, unit = "in") %>%
  width(j = 3, width = 2, unit = "in") %>%
  line_spacing(space = 1)
```