---
title: "Check values against SQL query versions of the same thing"
author: "M Siple"
date: "2023-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Setup channel to connect to Oracle --------------------------------------
source(here::here("R/setup_channel.R"))
# The setup_channel.R script sets up a channel using your Oracle username and pw.

# Get report settings -----------------------------------------------------
source("R/00_report_settings.R")

# Functions, packages, directories ---------------------------------------------
source("R/01_directories.R")
source("R/02_load_packages.R") 
```


```{r}

# Which survey number is it?
(survnumber)
survnumber_sql <- RODBC::sqlQuery(channel, "select count(distinct cruise) survnumber
from race_data.cruises a, race_data.survey_definitions b, race_data.surveys c
where b.survey_name = 'Aleutian Islands Bottom Trawl Survey'
and a.survey_id = c.survey_id
and b.survey_definition_id = c.survey_definition_id")

# What is the number of successfully sampled stations?
(nstations)
nstations_sql <- RODBC::sqlQuery(channel, "select count(distinct hauljoin) nstations
from racebase.haul
where region = 'AI'
and cruise = 202201
and abundance_haul = 'Y'")

# How many stations were assigned?
nstationsassigned_sql <- RODBC::sqlQuery(channel, "select count(*) new_stations from ai.station_allocation where year = 2022 and stationid is null")

nfishlengths_sql <- RODBC::sqlQuery(channel, "select count(*)
from racebase.length
where region = 'AI'
and cruise = 202201
and length_type in (1,5,11)")

nsquidlengths <- RODBC::sqlQuery(channel, "select count(*)
from racebase.length
where region = 'AI'
and cruise = 202201
and length_type=12")

```
# How many stations don't have Marport spread data?

```{r}
no_marport_data_sql <- RODBC::sqlQuery(channel, "select count(*) spread_measured
from racebase.haul
where region = 'AI'
and cruise = 202201
and net_measured = 'Y' -- always and only refers to net spread and indicates whether we modeled it (N) or measured it (Y)
and abundance_haul = 'Y'")
```

# Check summary of trawl effort for a given species - NEED TO TURN THIS INTO A FUNCTION
```{r}
atf_check_second_table_sql <- RODBC::sqlQuery(channel, "select distinct inpfc_area, min_depth||'-'||max_depth depth_range, haul_count, catch_count, mean_wgt_cpue/100 cpue_kg_ha, area_biomass, min_biomass, max_biomass
from goa.goa_strata a, ai.biomass_inpfc_depth b
where a.survey = 'AI'
and b.year = 2022
and b.species_code = 10110
and a.summary_area_depth = b.summary_area_depth
order by inpfc_area desc, depth_range")

```

# Check species richness with Sarah table
```{r}
x <- RODBC::sqlQuery(channel, "select a.cruise, decode(c.inpfc_area, 'Southern Bering Sea','Eastern Aleutians',c.inpfc_area) area_name, count(distinct b.species_code) elasmo_taxon_richness
from racebase.haul a, racebase.catch b, goa.goa_strata c
where a.region = 'AI'
and a.cruise >= 199101
and a.abundance_haul = 'Y'
and a.hauljoin = b.hauljoin
and b.species_code in (
select species_code
from racebase.species
where species_code between 150 and 711 -- sharks and skates
and species_name not like ('%egg%') -- eliminates records of egg cases
)
and a.region = c.survey
and a.stratum = c.stratum
group by a.cruise, decode(c.inpfc_area,'Southern Bering Sea','Eastern Aleutians',c.inpfc_area)
order by a.cruise, elasmo_taxon_richness desc")
ggplot(x, aes(x = CRUISE, y = ELASMO_TAXON_RICHNESS, color = AREA_NAME)) +
  geom_line()
```

## Checks

This script produces an easy-to-read table that compares the values produced in R to the ones produced by SQL queries, which used to be used to produce the data reports. 

```{r}
indiv_values <- data.frame("Variable name" = c("survnumber","nstations"),
                           "Description" = c("description 1","description 2"),
  "Value in previous report year" = c(NA,NA),
"Value this year from R" = c(survnumber,nstations)) %>%
  kableExtra::kable()
```


