---
output:
  officedown::rdocx_document: 
    reference_docx: styles_reference2.docx
    pandoc_args: ["--metadata-file=header.yaml"]
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography.bib"
---

This is a test of the cross-refs in this doc (Table \@ref(tab:stations-allocated)). And here is a test for figure cross-referencing (Figure \@ref(fig:area-map)).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
library(officedown)
library(officer)
```

```{r echo=FALSE}
# THESE STATIC VALUES ARE ALL FOR TESTING
# library(magrittr)
# #maxyr <- 2022
# #nth <- "10th"
# nfish <- 360 #UPDATE THESE
# ninverts <- 151
# nstations <- 390
# highest_total_catch <- c("Pacific cod (Gadus chalcogrammus),
#                          Arrowtooth flounder (Atherestes stomias)")
# # character vector. FIX and make list of species
# vessel1 <- "F/V Ocean Explorer"
# vessel2 <- "F/V Sea Storm"
# dates_conducted <- c("June 16th, 2022", "August 17th, 2022")
# 
# output_date <- "2022-08-24"
# load(here::here("output",paste(output_date),"figures","report_figures.rdata"))
# load(here::here("output",paste(output_date),"tables","report_tables.rdata"))

```

# Preface
```{r child=here::here("gdrive","Preface.Rmd")}
```

# Abstract
```{r child=here::here("gdrive","Abstract.Rmd")}
```

# Introduction
```{r child=here::here("gdrive","Introduction.Rmd")}
```

# Methods
```{r child=here::here("gdrive","Methods.Rmd")}
```

# Tables
```{r tab.cap='Stations allocated and sampled this year.', tab.id='stations-allocated',  tab.cap.style = "Table Caption"}
list_tables[[1]]
```

--
  
```{r tab.cap='Target numbers of length samples for each managed species.', tab.id='length-sample-sizes',  tab.cap.style = "Table Caption"}
list_tables[[2]]
```

# Figures
```{r fig.cap='Map of the Aleutian Islands 2018 bottom trawl survey area indicating survey districts (WAI = Western Aleutian Islands, CAI = Central Aleutian Islands, EAI = Eastern Aleutian Islands, and SBS = Southern Bering Sea), isobaths from 100–500 m and stations sampled (black dots).', fig.id='area-map',  tab.cap.style = "Figure Caption"}
list_figures[[1]]
```
