---
title: "Species result test"
output: word_document
params:
    speciescode: 30060
    commonname: "POP"
    middlesentences: "THESE ARE BESPOKE SENTENCES PASTED INTO THE MIDDLE OF THE BLURB"
    year: 2022
    region: "Aleutian Islands"
---

```{r, setup, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(echo = params$printcode)
# RENDER THIS REPORT USING:
# rmarkdown::render("ResultSpecies.Rmd", params = list(
#   year = 2022,
#   commonname = "POP",
#   middlesentences = "blah",
#   region = "Aleutian Islands",
#   speciescode = 30060
# ))
```

## This is a parameterized report
Here is my attempt to make this chapter based on the species code and the year that you put in `rmarkdown::render()`. Plus a few other things.

## `r paste0(params$commonname)`
This is the first sentence. `r paste(params$middlesentences)`. This is the last sentence.

```{r fig.cap=paste('Distribution and relative abundance of',params$commonname,'from the',params$year, params$region,'bottom trawl survey across the a) eastern, b) central, and c) western archipelago.'), fig.id='species-test',  tab.cap.style = "Figure Caption"}
plot(1:20,1:20)
```


