---
title: "TableTest"
author: "M Siple"
date: "2022-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set
library(magrittr)
library(kableExtra)
```

### Length count table
```{r echo=FALSE,warning=FALSE}
#ATF, NRS, poll, cod, Atka, sablefish, YIL, POP, BSRF, RERF, shortraker, Aleutian skate
length_counts <- read.csv(here::here("data","ned","length_counts.csv"))
length_counts <- length_counts %>% dplyr::rename("Common name" = "COMMON_NAME",
                                                 "Number of lengths" = "LENGTHS")
kableExtra::kable(length_counts, digits = 2) %>%
  kable_minimal()
```


### Otolith count table
```{r echo=FALSE,warning=FALSE}
otolith_pair_counts <- read.csv(here::here("data","ned","otolith_pair_counts.csv"))
otolith_pair_counts <- otolith_pair_counts %>%dplyr::rename("Common name" = "COMMON_NAME",
                                                 "Number of otoliths" = "OTOLITHS")
kableExtra::kable(otolith_pair_counts, digits = 2) %>%
  kable_minimal()
```