======TOTAL GOA SURVEY AREA IN 2023, DEPTHS <1000M ===============
SELECT SUM(AREA_KM2)
FROM GAP_PRODUCTS.AREA
WHERE SURVEY_DEFINITION_ID = 47
  AND DESIGN_YEAR = 1984
  AND AREA_TYPE = 'STRATUM'
  AND DEPTH_MAX_M < 1000

======TOTAL GOA SURVEY AREA IN 2023, DEPTHS <700M ===============
SELECT SUM(AREA_KM2)
FROM GAP_PRODUCTS.AREA
WHERE SURVEY_DEFINITION_ID = 47
  AND DESIGN_YEAR = 2025
  AND AREA_TYPE = 'STRATUM'
  AND DEPTH_MAX_M < 700

======TOTAL GOA SURVEY AREA IN 2025, DEPTHS <700M ===============

SELECT
    CASE
        WHEN AREA_NAME = 'Shumagin' THEN 610
        WHEN AREA_NAME = 'Chirikof' THEN 620
        WHEN AREA_NAME = 'Kodiak' THEN 630
        WHEN AREA_NAME = 'West Yakutat' THEN 640
        ELSE 650
    END NMFS_AREA,
    AREA_NAME,
    SUM(AREA_KM2) AS TOTAL_AREA_KM2,
    -- Calculate percent: (Sum of Group / Sum of All) * 100
    ROUND((SUM(AREA_KM2) / SUM(SUM(AREA_KM2)) OVER()) * 100, 2) AS AREA_PERCENTAGE
FROM GAP_PRODUCTS.AREA
WHERE SURVEY_DEFINITION_ID = 47
  AND DESIGN_YEAR = 2025
  AND AREA_TYPE = 'STRATUM'
  AND DEPTH_MAX_M < 1000
GROUP BY AREA_NAME
ORDER BY NMFS_AREA;
